name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure this secret is added in your GitHub repository

    - name: Verify Azure Login
      run: az account show

    - name: Build and push Docker image
      run: |
        set -x # Enable detailed shell output
        az acr login --name crudappregistry
        docker build -t crudappregistry.azurecr.io/crud-application:latest .
        docker push crudappregistry.azurecr.io/crud-application:latest
