name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Java version
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t vasistatummala/crud-application:latest .
          docker push vasistatummala/crud-application:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Log in to Azure with username and password
      - name: Log in to Azure
        run: |
          az login --username tummalavasista44@gmail.com --password Vasu@281201

      # Step 2: Configure kubectl with AKS
      - name: Set up AKS credentials
        run: |
          az aks get-credentials --resource-group crud-application-rg --name crud-app-aks

      # Step 3: Apply Combined Deployment and Service YAML
      - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f k8s/deployment.yaml
